# Generated by Django 3.1.7 on 2021-04-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210403_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recipes_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='recipes_liked',
            field=models.ManyToManyField(null=True, related_name='likes', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='recipes_saved',
            field=models.ManyToManyField(null=True, related_name='saves', to='recipes.Recipe'),
        ),
    ]
