# Generated by Django 3.1.7 on 2021-04-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210404_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recipes_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recipes_liked',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recipes_saved',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to='recipes.userprofile'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked_recipes', to='recipes.UserProfile'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_by',
            field=models.ManyToManyField(null=True, related_name='saved_recipes', to='recipes.UserProfile'),
        ),
    ]
